import {Reps} from '../../imports/api/collections/rep';
import {Categories} from '../../imports/api/collections/category';
import {Units} from '../../imports/api/collections/units';
import {AverageInventories} from '../../imports/api/collections/inventory';
import {Customers} from '../../imports/api/collections/customer';
import {Vendors} from '../../imports/api/collections/vendor';
import {CompanyExchangeRingPulls} from '../../imports/api/collections/companyExchangeRingPull';
import {EnterBills} from '../../imports/api/collections/enterBill';
import {ExchangeRingPulls} from '../../imports/api/collections/exchangeRingPull';
import {GratisInventories} from '../../imports/api/collections/gratisInventory';
import {Invoices} from '../../imports/api/collections/invoice';
import {GroupInvoice} from '../../imports/api/collections/groupInvoice';
import {Item} from '../../imports/api/collections/item';
import {LendingStocks} from '../../imports/api/collections/lendingStock';
import {LocationTransfers} from '../../imports/api/collections/locationTransfer';
import {PayBills} from '../../imports/api/collections/payBill';
import {PrepaidOrders} from '../../imports/api/collections/prepaidOrder';
import {ReceiveItems} from '../../imports/api/collections/receiveItem';
import {ReceivePayment} from '../../imports/api/collections/receivePayment';
import {RingPullInventories} from '../../imports/api/collections/ringPullInventory';
import {RingPullTransfers} from '../../imports/api/collections/ringPullTransfer';
import {TransferMoney} from '../../imports/api/collections/transferMoney';
import {Order} from '../../imports/api/collections/order';
import {InventoryDates} from '../../imports/api/collections/inventoryDate';
import {ConvertItems} from '../../imports/api/collections/convertItem';
import {Journal} from '../../../acc/imports/api/collections/journal';
import {DateEndOfProcess} from '../../../acc/imports/api/collections/dateEndOfProcess';
import {NetInCome} from '../../../acc/imports/api/collections/netIncome';
import {CloseChartAccount} from '../../../acc/imports/api/collections/closeChartAccount';
import {CloseChartAccountPerMonth} from '../../../acc/imports/api/collections/closeChartAccountPerMonth';
import {Closing} from '../../../acc/imports/api/collections/closing';
import {FixAssetExpense} from '../../../acc/imports/api/collections/fixAssetExpense';
import {StockLocations} from '../../imports/api/collections/stockLocation';
import {StockAndAccountMapping} from '../../imports/api/collections/stockAndAccountMapping';
import {ItemPriceForCustomers} from '../../imports/api/collections/itemPriceForCustomer';
import {QuantityRangeMapping} from '../../imports/api/collections/quantityRangeMapping';
import {Terms} from '../../imports/api/collections/terms';
import {PaymentGroups} from '../../imports/api/collections/paymentGroup';
import {Location} from '../../imports/api/collections/location';
Meteor.methods({
    removeAllData() {
        //remove all data except some setting
        Units.direct.remove({});
        AverageInventories.direct.remove({});
        Categories.direct.remove({});
        CompanyExchangeRingPulls.direct.remove({});
        EnterBills.direct.remove({});
        ExchangeRingPulls.direct.remove({});
        GratisInventories.direct.remove({});
        Invoices.direct.remove({});
        GroupInvoice.direct.remove({});
        Item.direct.remove({});
        LendingStocks.direct.remove({});
        LocationTransfers.direct.remove({});
        PayBills.direct.remove({});
        PrepaidOrders.direct.remove({});
        ReceiveItems.direct.remove({});
        ReceivePayment.direct.remove({});
        RingPullInventories.direct.remove({});
        RingPullTransfers.direct.remove({});
        TransferMoney.direct.remove({});
        Order.direct.remove({});
        InventoryDates.direct.remove({});
        ConvertItems.direct.remove({});
        //clear acc
        Journal.direct.remove({});
        DateEndOfProcess.direct.remove({});
        NetInCome.direct.remove({});
        CloseChartAccount.direct.remove({});
        CloseChartAccountPerMonth.direct.remove({});
        Closing.direct.remove({});
        FixAssetExpense.direct.remove({});
        Customers.direct.remove({});
        Vendors.direct.remove({});
        Reps.direct.remove({});
        StockLocations.direct.remove({});
        StockAndAccountMapping.direct.remove({});
        Terms.direct.remove({});
        Location.direct.remove({});
        QuantityRangeMapping.direct.remove({});
        return;
    },
    removeAllTransaction(){
        //remove all data except some setting
        AverageInventories.direct.remove({});
        CompanyExchangeRingPulls.direct.remove({});
        EnterBills.direct.remove({});
        ExchangeRingPulls.direct.remove({});
        GratisInventories.direct.remove({});
        Invoices.direct.remove({});
        GroupInvoice.direct.remove({});
        Item.direct.update({}, {$unset: {qtyOnHand: ''}}, {multi: true});
        LendingStocks.direct.remove({});
        LocationTransfers.direct.remove({});
        PayBills.direct.remove({});
        PrepaidOrders.direct.remove({});
        ReceiveItems.direct.remove({});
        ReceivePayment.direct.remove({});
        RingPullInventories.direct.remove({});
        RingPullTransfers.direct.remove({});
        TransferMoney.direct.remove({});
        Order.direct.remove({});
        InventoryDates.direct.remove({});
        ConvertItems.direct.remove({});
        //clear acc
        Journal.direct.remove({});
        DateEndOfProcess.direct.remove({});
        NetInCome.direct.remove({});
        CloseChartAccount.direct.remove({});
        CloseChartAccountPerMonth.direct.remove({});
        Closing.direct.remove({});
        FixAssetExpense.direct.remove({});
        return;
    }
});
